{% set name = "pystackreg" %}
{% set version = "0.2.2" %}
{% set sha256 = "2bc8bdac892bb827cd2725b8ee45bbcdb8835f2fb1d41863f6d50c77f7e36ccc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pip
  run:
    - numpy
    - python
    - tqdm

test:
  imports:
    - pystackreg

about:
  home: "https://bitbucket.org/glichtner/pystackreg"
  license: UNKNOWN
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Python implementation of the ImageJ/FIJI Plugin TurboReg/StackReg
